version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app:rw
    command: >
      sh -c "npm install && npm run dev"


